insert into banks (number, title_color, body_color, name) values
('002', null, null, 'BANCO CENTRAL DO BRASIL'),
('001', null, null, 'BANCO DO BRASIL S/A'),
('003', null, null, 'BANCO DA AMAZONIA S.A'),
('007', null, null, 'BANCO NAC DESENV. ECO. SOCIAL S.A'),
('004', null, null, 'BANCO DO NORDESTE DO BRASIL S.A'),
('008', null, null, 'BANCO MERIDIONAL DO BRASIL'),
('020', null, null, 'BANCO DO ESTADO DE ALAGOAS S.A'),
('021', null, null, 'BANCO DO ESTADO DO ESPIRITO SANTO S.A'),
('022', null, null, 'BANCO DE CREDITO REAL DE MINAS GERAIS SA'),
('024', null, null, 'BANCO DO ESTADO DE PERNAMBUCO'),
('025', null, null, 'BANCO ALFA S/A'),
('026', null, null, 'BANCO DO ESTADO DO ACRE S.A'),
('027', null, null, 'BANCO DO ESTADO DE SANTA CATARINA S.A'),
('028', null, null, 'BANCO DO ESTADO DA BAHIA S.A'),
('029', null, null, 'BANCO DO ESTADO DO RIO DE JANEIRO S.A'),
('030', null, null, 'BANCO DO ESTADO DA PARAIBA S.A'),
('031', null, null, 'BANCO DO ESTADO DE GOIAS S.A'),
('032', null, null, 'BANCO DO ESTADO DO MATO GROSSO S.A.'),
('033', null, null, 'BANCO DO ESTADO DE SAO PAULO S.A'),
('034', null, null, 'BANCO DO ESADO DO AMAZONAS S.A'),
('035', null, null, 'BANCO DO ESTADO DO CEARA S.A'),
('036', null, null, 'BANCO DO ESTADO DO MARANHAO S.A'),
('037', null, null, 'BANCO DO ESTADO DO PARA S.A'),
('038', null, null, 'BANCO DO ESTADO DO PARANA S.A'),
('039', null, null, 'BANCO DO ESTADO DO PIAUI S.A'),
('041', null, null, 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A'),
('047', null, null, 'BANCO DO ESTADO DE SERGIPE S.A'),
('048', null, null, 'BANCO DO ESTADO DE MINAS GERAIS S.A'),
('059', null, null, 'BANCO DO ESTADO DE RONDONIA S.A'),
('070', null, null, 'BANCO DE BRASILIA S.A'),
('077', null, null, 'BANCO INTER S.A'),
('102', null, null, 'XP INVESTIMENTOS'),
('104', '#0369b9', '#f3bb5c', 'CAIXA ECONOMICA FEDERAL'),
('106', null, null, 'BANCO ITABANCO S.A.'),
('107', null, null, 'BANCO BBM S.A'),
('109', null, null, 'BANCO CREDIBANCO S.A'),
('116', null, null, 'BANCO B.N.L DO BRASIL S.A'),
('148', null, null, 'MULTI BANCO S.A'),
('151', null, null, 'CAIXA ECONOMICA DO ESTADO DE SAO PAULO'),
('153', null, null, 'CAIXA ECONOMICA DO ESTADO DO R.G.SUL'),
('165', null, null, 'BANCO NORCHEM S.A'),
('166', null, null, 'BANCO INTER-ATLANTICO S.A'),
('168', null, null, 'BANCO C.C.F. BRASIL S.A'),
('175', null, null, 'CONTINENTAL BANCO S.A'),
('184', null, null, 'BBA - CREDITANSTALT S.A'),
('199', null, null, 'BANCO FINANCIAL PORTUGUES'),
('200', null, null, 'BANCO FRICRISA AXELRUD S.A'),
('201', null, null, 'BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A'),
('204', null, null, 'BANCO S.R.L S.A'),
('205', null, null, 'BANCO SUL AMERICA S.A'),
('206', null, null, 'BANCO MARTINELLI S.A'),
('208', null, null, 'BANCO PACTUAL S.A'),
('210', null, null, 'DEUTSCH SUDAMERIKANICHE BANK AG'),
('211', null, null, 'BANCO SISTEMA S.A'),
('212', null, null, 'BANCO MATONE S.A'),
('213', null, null, 'BANCO ARBI S.A'),
('214', null, null, 'BANCO DIBENS S.A'),
('215', null, null, 'BANCO AMERICA DO SUL S.A'),
('216', null, null, 'BANCO REGIONAL MALCON S.A'),
('217', null, null, 'BANCO AGROINVEST S.A'),
('218', null, null, 'BBS - BANCO BONSUCESSO S.A.'),
('219', null, null, 'BANCO DE CREDITO DE SAO PAULO S.A'),
('220', null, null, 'BANCO CREFISUL'),
('221', null, null, 'BANCO GRAPHUS S.A'),
('222', null, null, 'BANCO AGF BRASIL S. A.'),
('223', null, null, 'BANCO INTERUNION S.A'),
('224', null, null, 'BANCO FIBRA S.A'),
('225', null, null, 'BANCO BRASCAN S.A'),
('228', null, null, 'BANCO ICATU S.A'),
('229', null, null, 'BANCO CRUZEIRO S.A'),
('230', null, null, 'BANCO BANDEIRANTES S.A'),
('231', null, null, 'BANCO BOAVISTA S.A'),
('232', null, null, 'BANCO INTERPART S.A'),
('233', null, null, 'BANCO MAPPIN S.A'),
('234', null, null, 'BANCO LAVRA S.A.'),
('235', null, null, 'BANCO LIBERAL S.A'),
('236', null, null, 'BANCO CAMBIAL S.A'),
('237', null, null, 'BANCO BRADESCO S.A'),
('239', null, null, 'BANCO BANCRED S.A'),
('240', null, null, 'BANCO DE CREDITO REAL DE MINAS GERAIS S.'),
('241', null, null, 'BANCO CLASSICO S.A'),
('242', null, null, 'BANCO EUROINVEST S.A'),
('243', null, null, 'BANCO STOCK S.A'),
('244', null, null, 'BANCO CIDADE S.A'),
('245', null, null, 'BANCO EMPRESARIAL S.A'),
('246', null, null, 'BANCO ABC ROMA S.A'),
('247', null, null, 'BANCO OMEGA S.A'),
('249', null, null, 'BANCO INVESTCRED S.A'),
('250', null, null, 'BANCO SCHAHIN CURY S.A'),
('251', null, null, 'BANCO SAO JORGE S.A.'),
('252', null, null, 'BANCO FININVEST S.A'),
('254', null, null, 'BANCO PARANA BANCO S.A'),
('255', null, null, 'MILBANCO S.A.'),
('256', null, null, 'BANCO GULVINVEST S.A'),
('258', null, null, 'BANCO INDUSCRED S.A'),
('260', '#ba4de3', '#d494ec', 'NUBANK S.A'),
('261', null, null, 'BANCO VARIG S.A'),
('262', null, null, 'BANCO BOREAL S.A'),
('263', null, null, 'BANCO CACIQUE'),
('264', null, null, 'BANCO PERFORMANCE S.A'),
('265', null, null, 'BANCO FATOR S.A'),
('266', null, null, 'BANCO CEDULA S.A'),
('267', null, null, 'BANCO BBM-COM.C.IMOB.CFI S.A.'),
('275', null, null, 'BANCO REAL S.A'),
('277', null, null, 'BANCO PLANIBANC S.A'),
('282', null, null, 'BANCO BRASILEIRO COMERCIAL'),
('291', null, null, 'BANCO DE CREDITO NACIONAL S.A'),
('294', null, null, 'BCR - BANCO DE CREDITO REAL S.A'),
('295', null, null, 'BANCO CREDIPLAN S.A'),
('300', null, null, 'BANCO DE LA NACION ARGENTINA S.A'),
('302', null, null, 'BANCO DO PROGRESSO S.A'),
('303', null, null, 'BANCO HNF S.A.'),
('304', null, null, 'BANCO PONTUAL S.A'),
('308', null, null, 'BANCO COMERCIAL BANCESA S.A.'),
('318', null, null, 'BANCO B.M.G. S.A'),
('320', null, null, 'BANCO INDUSTRIAL E COMERCIAL'),
('341', null, null, 'BANCO ITAU S.A'),
('346', null, null, 'BANCO FRANCES E BRASILEIRO S.A'),
('347', null, null, 'BANCO SUDAMERIS BRASIL S.A'),
('351', null, null, 'BANCO BOZANO SIMONSEN S.A'),
('353', null, null, 'BANCO GERAL DO COMERCIO S.A'),
('356', null, null, 'ABN AMRO S.A'),
('366', null, null, 'BANCO SOGERAL S.A'),
('369', null, null, 'PONTUAL'),
('370', null, null, 'BEAL - BANCO EUROPEU PARA AMERICA LATINA'),
('372', null, null, 'BANCO ITAMARATI S.A'),
('375', null, null, 'BANCO FENICIA S.A'),
('376', null, null, 'CHASE MANHATTAN BANK S.A'),
('388', null, null, 'BANCO MERCANTIL DE DESCONTOS S/A'),
('389', null, null, 'BANCO MERCANTIL DO BRASIL S.A'),
('392', null, null, 'BANCO MERCANTIL DE SAO PAULO S.A'),
('394', null, null, 'BANCO B.M.C. S.A'),
('399', null, null, 'BANCO BAMERINDUS DO BRASIL S.A'),
('409', null, null, 'UNIBANCO - UNIAO DOS BANCOS BRASILEIROS'),
('412', null, null, 'BANCO NACIONAL DA BAHIA S.A'),
('415', null, null, 'BANCO NACIONAL S.A'),
('420', null, null, 'BANCO NACIONAL DO NORTE S.A'),
('422', null, null, 'BANCO SAFRA S.A'),
('424', null, null, 'BANCO NOROESTE S.A'),
('434', null, null, 'BANCO FORTALEZA S.A'),
('453', null, null, 'BANCO RURAL S.A'),
('456', null, null, 'BANCO TOKIO S.A'),
('464', null, null, 'BANCO SUMITOMO BRASILEIRO S.A'),
('466', null, null, 'BANCO MITSUBISHI BRASILEIRO S.A'),
('472', null, null, 'LLOYDS BANK PLC'),
('473', null, null, 'BANCO FINANCIAL PORTUGUES S.A'),
('477', null, null, 'CITIBANK N.A'),
('479', null, null, 'BANCO DE BOSTON S.A'),
('480', null, null, 'BANCO PORTUGUES DO ATLANTICO-BRASIL S.A'),
('483', null, null, 'BANCO AGRIMISA S.A.'),
('487', null, null, 'DEUTSCHE BANK S.A - BANCO ALEMAO'),
('488', null, null, 'BANCO J. P. MORGAN S.A'),
('489', null, null, 'BANESTO BANCO URUGAUAY S.A'),
('492', null, null, 'INTERNATIONALE NEDERLANDEN BANK N.V.'),
('493', null, null, 'BANCO UNION S.A.C.A'),
('494', null, null, 'BANCO LA REP. ORIENTAL DEL URUGUAY'),
('495', null, null, 'BANCO LA PROVINCIA DE BUENOS AIRES'),
('496', null, null, 'BANCO EXTERIOR DE ESPANA S.A'),
('498', null, null, 'CENTRO HISPANO BANCO'),
('499', null, null, 'BANCO IOCHPE S.A'),
('501', null, null, 'BANCO BRASILEIRO IRAQUIANO S.A.'),
('502', null, null, 'BANCO SANTANDER S.A'),
('504', null, null, 'BANCO MULTIPLIC S.A'),
('505', null, null, 'BANCO GARANTIA S.A'),
('600', null, null, 'BANCO LUSO BRASILEIRO S.A'),
('601', null, null, 'BFC BANCO S.A.'),
('602', null, null, 'BANCO PATENTE S.A'),
('604', null, null, 'BANCO INDUSTRIAL DO BRASIL S.A'),
('607', null, null, 'BANCO SANTOS NEVES S.A'),
('608', null, null, 'BANCO OPEN S.A'),
('610', null, null, 'BANCO V.R. S.A'),
('611', null, null, 'BANCO PAULISTA S.A'),
('612', null, null, 'BANCO GUANABARA S.A'),
('613', null, null, 'BANCO PECUNIA S.A'),
('616', null, null, 'BANCO INTERPACIFICO S.A'),
('617', null, null, 'BANCO INVESTOR S.A.'),
('618', null, null, 'BANCO TENDENCIA S.A'),
('621', null, null, 'BANCO APLICAP S.A.'),
('622', null, null, 'BANCO DRACMA S.A'),
('623', null, null, 'BANCO PANAMERICANO S.A'),
('624', null, null, 'BANCO GENERAL MOTORS S.A'),
('625', null, null, 'BANCO ARAUCARIA S.A'),
('626', null, null, 'BANCO FICSA S.A'),
('627', null, null, 'BANCO DESTAK S.A'),
('628', null, null, 'BANCO CRITERIUM S.A'),
('629', null, null, 'BANCORP BANCO COML. E. DE INVESTMENTO'),
('630', null, null, 'BANCO INTERCAP S.A'),
('633', null, null, 'BANCO REDIMENTO S.A'),
('634', null, null, 'BANCO TRIANGULO S.A'),
('635', null, null, 'BANCO DO ESTADO DO AMAPA S.A'),
('637', null, null, 'BANCO SOFISA S.A'),
('638', null, null, 'BANCO PROSPER S.A'),
('639', null, null, 'BIG S.A. - BANCO IRMAOS GUIMARAES'),
('640', null, null, 'BANCO DE CREDITO METROPOLITANO S.A'),
('641', null, null, 'BANCO EXCEL ECONOMICO S/A'),
('643', null, null, 'BANCO SEGMENTO S.A'),
('645', null, null, 'BANCO DO ESTADO DE RORAIMA S.A'),
('647', null, null, 'BANCO MARKA S.A'),
('648', null, null, 'BANCO ATLANTIS S.A'),
('649', null, null, 'BANCO DIMENSAO S.A'),
('650', null, null, 'BANCO PEBB S.A'),
('652', null, null, 'BANCO FRANCES E BRASILEIRO SA'),
('653', null, null, 'BANCO INDUSVAL S.A'),
('654', null, null, 'BANCO A. J. RENNER S.A'),
('655', null, null, 'BANCO VOTORANTIM S.A.'),
('656', null, null, 'BANCO MATRIX S.A'),
('657', null, null, 'BANCO TECNICORP S.A'),
('658', null, null, 'BANCO PORTO REAL S.A'),
('702', null, null, 'BANCO SANTOS S.A'),
('705', null, null, 'BANCO INVESTCORP S.A.'),
('707', null, null, 'BANCO DAYCOVAL S.A'),
('711', null, null, 'BANCO VETOR S.A.'),
('713', null, null, 'BANCO CINDAM S.A'),
('715', null, null, 'BANCO VEGA S.A'),
('718', null, null, 'BANCO OPERADOR S.A'),
('719', null, null, 'BANCO PRIMUS S.A'),
('720', null, null, 'BANCO MAXINVEST S.A'),
('721', null, null, 'BANCO CREDIBEL S.A'),
('722', null, null, 'BANCO INTERIOR DE SAO PAULO S.A'),
('724', null, null, 'BANCO PORTO SEGURO S.A'),
('725', null, null, 'BANCO FINABANCO S.A'),
('726', null, null, 'BANCO UNIVERSAL S.A'),
('728', null, null, 'BANCO FITAL S.A'),
('729', null, null, 'BANCO FONTE S.A'),
('730', null, null, 'BANCO COMERCIAL PARAGUAYO S.A'),
('731', null, null, 'BANCO GNPP S.A.'),
('732', null, null, 'BANCO PREMIER S.A.'),
('733', null, null, 'BANCO NACOES S.A.'),
('734', null, null, 'BANCO GERDAU S.A'),
('735', null, null, 'BANCO NEON'),
('736', null, null, 'BANCO UNITED S.A'),
('737', null, null, 'THECA'),
('738', null, null, 'MARADA'),
('739', null, null, 'BGN'),
('740', null, null, 'BCN BARCLAYS'),
('741', null, null, 'BRP'),
('742', null, null, 'EQUATORIAL'),
('743', null, null, 'BANCO EMBLEMA S.A'),
('744', null, null, 'THE FIRST NATIONAL BANK OF BOSTON'),
('745', null, null, 'CITIBAN N.A.'),
('746', null, null, 'MODAL S\A'),
('747', null, null, 'RAIBOBANK DO BRASIL'),
('748', null, null, 'SICREDI'),
('749', null, null, 'BRMSANTIL SA'),
('750', null, null, 'BANCO REPUBLIC NATIONAL OF NEW YORK (BRA'),
('751', null, null, 'DRESDNER BANK LATEINAMERIKA-BRASIL S/A'),
('752', null, null, 'BANCO BANQUE NATIONALE DE PARIS BRASIL S'),
('753', null, null, 'BANCO COMERCIAL URUGUAI S.A.'),
('755', null, null, 'BANCO MERRILL LYNCH S.A'),
('756', null, null, 'BANCO COOPERATIVO DO BRASIL S.A.'),
('757', null, null, 'BANCO KEB DO BRASIL S.A.')