<?php

use Illuminate\Database\Seeder;
use App\Models\Bank;

class BanksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(Bank::where('id', '>', 0)->count() === 0){
            Bank::create(['Number' => '001', 'Name' => 'BANCO DO BRASIL S/A']);
            Bank::create(['Number' => '002', 'Name' => 'BANCO CENTRAL DO BRASIL']);
            Bank::create(['Number' => '003', 'Name' => 'BANCO DA AMAZONIA S.A']);
            Bank::create(['Number' => '004', 'Name' => 'BANCO DO NORDESTE DO BRASIL S.A']);
            Bank::create(['Number' => '007', 'Name' => 'BANCO NAC DESENV. ECO. SOCIAL S.A']);
            Bank::create(['Number' => '008', 'Name' => 'BANCO MERIDIONAL DO BRASIL']);
            Bank::create(['Number' => '020', 'Name' => 'BANCO DO ESTADO DE ALAGOAS S.A']);
            Bank::create(['Number' => '021', 'Name' => 'BANCO DO ESTADO DO ESPIRITO SANTO S.A']);
            Bank::create(['Number' => '022', 'Name' => 'BANCO DE CREDITO REAL DE MINAS GERAIS SA']);
            Bank::create(['Number' => '024', 'Name' => 'BANCO DO ESTADO DE PERNAMBUCO']);
            Bank::create(['Number' => '025', 'Name' => 'BANCO ALFA S/A']);
            Bank::create(['Number' => '026', 'Name' => 'BANCO DO ESTADO DO ACRE S.A']);
            Bank::create(['Number' => '027', 'Name' => 'BANCO DO ESTADO DE SANTA CATARINA S.A']);
            Bank::create(['Number' => '028', 'Name' => 'BANCO DO ESTADO DA BAHIA S.A']);
            Bank::create(['Number' => '029', 'Name' => 'BANCO DO ESTADO DO RIO DE JANEIRO S.A']);
            Bank::create(['Number' => '030', 'Name' => 'BANCO DO ESTADO DA PARAIBA S.A']);
            Bank::create(['Number' => '031', 'Name' => 'BANCO DO ESTADO DE GOIAS S.A']);
            Bank::create(['Number' => '032', 'Name' => 'BANCO DO ESTADO DO MATO GROSSO S.A.']);
            Bank::create(['Number' => '033', 'Name' => 'BANCO DO ESTADO DE SAO PAULO S.A']);
            Bank::create(['Number' => '034', 'Name' => 'BANCO DO ESADO DO AMAZONAS S.A']);
            Bank::create(['Number' => '035', 'Name' => 'BANCO DO ESTADO DO CEARA S.A']);
            Bank::create(['Number' => '036', 'Name' => 'BANCO DO ESTADO DO MARANHAO S.A']);
            Bank::create(['Number' => '037', 'Name' => 'BANCO DO ESTADO DO PARA S.A']);
            Bank::create(['Number' => '038', 'Name' => 'BANCO DO ESTADO DO PARANA S.A']);
            Bank::create(['Number' => '039', 'Name' => 'BANCO DO ESTADO DO PIAUI S.A']);
            Bank::create(['Number' => '041', 'Name' => 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A']);
            Bank::create(['Number' => '047', 'Name' => 'BANCO DO ESTADO DE SERGIPE S.A']);
            Bank::create(['Number' => '048', 'Name' => 'BANCO DO ESTADO DE MINAS GERAIS S.A']);
            Bank::create(['Number' => '059', 'Name' => 'BANCO DO ESTADO DE RONDONIA S.A']);
            Bank::create(['Number' => '070', 'Name' => 'BANCO DE BRASILIA S.A']);
            Bank::create(['Number' => '077', 'Name' => 'BANCO INTER S.A']);
            Bank::create(['Number' => '102', 'Name' => 'XP INVESTIMENTOS']);
            Bank::create(['Number' => '104', 'Name' => 'CAIXA ECONOMICA FEDERAL']);
            Bank::create(['Number' => '106', 'Name' => 'BANCO ITABANCO S.A.']);
            Bank::create(['Number' => '107', 'Name' => 'BANCO BBM S.A']);
            Bank::create(['Number' => '109', 'Name' => 'BANCO CREDIBANCO S.A']);
            Bank::create(['Number' => '116', 'Name' => 'BANCO B.N.L DO BRASIL S.A']);
            Bank::create(['Number' => '148', 'Name' => 'MULTI BANCO S.A']);
            Bank::create(['Number' => '151', 'Name' => 'CAIXA ECONOMICA DO ESTADO DE SAO PAULO']);
            Bank::create(['Number' => '153', 'Name' => 'CAIXA ECONOMICA DO ESTADO DO R.G.SUL']);
            Bank::create(['Number' => '165', 'Name' => 'BANCO NORCHEM S.A']);
            Bank::create(['Number' => '166', 'Name' => 'BANCO INTER-ATLANTICO S.A']);
            Bank::create(['Number' => '168', 'Name' => 'BANCO C.C.F. BRASIL S.A']);
            Bank::create(['Number' => '175', 'Name' => 'CONTINENTAL BANCO S.A']);
            Bank::create(['Number' => '184', 'Name' => 'BBA - CREDITANSTALT S.A']);
            Bank::create(['Number' => '199', 'Name' => 'BANCO FINANCIAL PORTUGUES']);
            Bank::create(['Number' => '200', 'Name' => 'BANCO FRICRISA AXELRUD S.A']);
            Bank::create(['Number' => '201', 'Name' => 'BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A']);
            Bank::create(['Number' => '204', 'Name' => 'BANCO S.R.L S.A']);
            Bank::create(['Number' => '205', 'Name' => 'BANCO SUL AMERICA S.A']);
            Bank::create(['Number' => '206', 'Name' => 'BANCO MARTINELLI S.A']);
            Bank::create(['Number' => '208', 'Name' => 'BANCO PACTUAL S.A']);
            Bank::create(['Number' => '210', 'Name' => 'DEUTSCH SUDAMERIKANICHE BANK AG']);
            Bank::create(['Number' => '211', 'Name' => 'BANCO SISTEMA S.A']);
            Bank::create(['Number' => '212', 'Name' => 'BANCO MATONE S.A']);
            Bank::create(['Number' => '213', 'Name' => 'BANCO ARBI S.A']);
            Bank::create(['Number' => '214', 'Name' => 'BANCO DIBENS S.A']);
            Bank::create(['Number' => '215', 'Name' => 'BANCO AMERICA DO SUL S.A']);
            Bank::create(['Number' => '216', 'Name' => 'BANCO REGIONAL MALCON S.A']);
            Bank::create(['Number' => '217', 'Name' => 'BANCO AGROINVEST S.A']);
            Bank::create(['Number' => '218', 'Name' => 'BBS - BANCO BONSUCESSO S.A.']);
            Bank::create(['Number' => '219', 'Name' => 'BANCO DE CREDITO DE SAO PAULO S.A']);
            Bank::create(['Number' => '220', 'Name' => 'BANCO CREFISUL']);
            Bank::create(['Number' => '221', 'Name' => 'BANCO GRAPHUS S.A']);
            Bank::create(['Number' => '222', 'Name' => 'BANCO AGF BRASIL S. A.']);
            Bank::create(['Number' => '223', 'Name' => 'BANCO INTERUNION S.A']);
            Bank::create(['Number' => '224', 'Name' => 'BANCO FIBRA S.A']);
            Bank::create(['Number' => '225', 'Name' => 'BANCO BRASCAN S.A']);
            Bank::create(['Number' => '228', 'Name' => 'BANCO ICATU S.A']);
            Bank::create(['Number' => '229', 'Name' => 'BANCO CRUZEIRO S.A']);
            Bank::create(['Number' => '230', 'Name' => 'BANCO BANDEIRANTES S.A']);
            Bank::create(['Number' => '231', 'Name' => 'BANCO BOAVISTA S.A']);
            Bank::create(['Number' => '232', 'Name' => 'BANCO INTERPART S.A']);
            Bank::create(['Number' => '233', 'Name' => 'BANCO MAPPIN S.A']);
            Bank::create(['Number' => '234', 'Name' => 'BANCO LAVRA S.A.']);
            Bank::create(['Number' => '235', 'Name' => 'BANCO LIBERAL S.A']);
            Bank::create(['Number' => '236', 'Name' => 'BANCO CAMBIAL S.A']);
            Bank::create(['Number' => '237', 'Name' => 'BANCO BRADESCO S.A']);
            Bank::create(['Number' => '239', 'Name' => 'BANCO BANCRED S.A']);
            Bank::create(['Number' => '240', 'Name' => 'BANCO DE CREDITO REAL DE MINAS GERAIS S.']);
            Bank::create(['Number' => '241', 'Name' => 'BANCO CLASSICO S.A']);
            Bank::create(['Number' => '242', 'Name' => 'BANCO EUROINVEST S.A']);
            Bank::create(['Number' => '243', 'Name' => 'BANCO STOCK S.A']);
            Bank::create(['Number' => '244', 'Name' => 'BANCO CIDADE S.A']);
            Bank::create(['Number' => '245', 'Name' => 'BANCO EMPRESARIAL S.A']);
            Bank::create(['Number' => '246', 'Name' => 'BANCO ABC ROMA S.A']);
            Bank::create(['Number' => '247', 'Name' => 'BANCO OMEGA S.A']);
            Bank::create(['Number' => '249', 'Name' => 'BANCO INVESTCRED S.A']);
            Bank::create(['Number' => '250', 'Name' => 'BANCO SCHAHIN CURY S.A']);
            Bank::create(['Number' => '251', 'Name' => 'BANCO SAO JORGE S.A.']);
            Bank::create(['Number' => '252', 'Name' => 'BANCO FININVEST S.A']);
            Bank::create(['Number' => '254', 'Name' => 'BANCO PARANA BANCO S.A']);
            Bank::create(['Number' => '255', 'Name' => 'MILBANCO S.A.']);
            Bank::create(['Number' => '256', 'Name' => 'BANCO GULVINVEST S.A']);
            Bank::create(['Number' => '258', 'Name' => 'BANCO INDUSCRED S.A']);
            Bank::create(['Number' => '260', 'Name' => 'NUBANK S.A']);
            Bank::create(['Number' => '261', 'Name' => 'BANCO VARIG S.A']);
            Bank::create(['Number' => '262', 'Name' => 'BANCO BOREAL S.A']);
            Bank::create(['Number' => '263', 'Name' => 'BANCO CACIQUE']);
            Bank::create(['Number' => '264', 'Name' => 'BANCO PERFORMANCE S.A']);
            Bank::create(['Number' => '265', 'Name' => 'BANCO FATOR S.A']);
            Bank::create(['Number' => '266', 'Name' => 'BANCO CEDULA S.A']);
            Bank::create(['Number' => '267', 'Name' => 'BANCO BBM-COM.C.IMOB.CFI S.A.']);
            Bank::create(['Number' => '275', 'Name' => 'BANCO REAL S.A']);
            Bank::create(['Number' => '277', 'Name' => 'BANCO PLANIBANC S.A']);
            Bank::create(['Number' => '282', 'Name' => 'BANCO BRASILEIRO COMERCIAL']);
            Bank::create(['Number' => '291', 'Name' => 'BANCO DE CREDITO NACIONAL S.A']);
            Bank::create(['Number' => '294', 'Name' => 'BCR - BANCO DE CREDITO REAL S.A']);
            Bank::create(['Number' => '295', 'Name' => 'BANCO CREDIPLAN S.A']);
            Bank::create(['Number' => '300', 'Name' => 'BANCO DE LA NACION ARGENTINA S.A']);
            Bank::create(['Number' => '302', 'Name' => 'BANCO DO PROGRESSO S.A']);
            Bank::create(['Number' => '303', 'Name' => 'BANCO HNF S.A.']);
            Bank::create(['Number' => '304', 'Name' => 'BANCO PONTUAL S.A']);
            Bank::create(['Number' => '308', 'Name' => 'BANCO COMERCIAL BANCESA S.A.']);
            Bank::create(['Number' => '318', 'Name' => 'BANCO B.M.G. S.A']);
            Bank::create(['Number' => '320', 'Name' => 'BANCO INDUSTRIAL E COMERCIAL']);
            Bank::create(['Number' => '341', 'Name' => 'BANCO ITAU S.A']);
            Bank::create(['Number' => '346', 'Name' => 'BANCO FRANCES E BRASILEIRO S.A']);
            Bank::create(['Number' => '347', 'Name' => 'BANCO SUDAMERIS BRASIL S.A']);
            Bank::create(['Number' => '351', 'Name' => 'BANCO BOZANO SIMONSEN S.A']);
            Bank::create(['Number' => '353', 'Name' => 'BANCO GERAL DO COMERCIO S.A']);
            Bank::create(['Number' => '356', 'Name' => 'ABN AMRO S.A']);
            Bank::create(['Number' => '366', 'Name' => 'BANCO SOGERAL S.A']);
            Bank::create(['Number' => '369', 'Name' => 'PONTUAL']);
            Bank::create(['Number' => '370', 'Name' => 'BEAL - BANCO EUROPEU PARA AMERICA LATINA']);
            Bank::create(['Number' => '372', 'Name' => 'BANCO ITAMARATI S.A']);
            Bank::create(['Number' => '375', 'Name' => 'BANCO FENICIA S.A']);
            Bank::create(['Number' => '376', 'Name' => 'CHASE MANHATTAN BANK S.A']);
            Bank::create(['Number' => '388', 'Name' => 'BANCO MERCANTIL DE DESCONTOS S/A']);
            Bank::create(['Number' => '389', 'Name' => 'BANCO MERCANTIL DO BRASIL S.A']);
            Bank::create(['Number' => '392', 'Name' => 'BANCO MERCANTIL DE SAO PAULO S.A']);
            Bank::create(['Number' => '394', 'Name' => 'BANCO B.M.C. S.A']);
            Bank::create(['Number' => '399', 'Name' => 'BANCO BAMERINDUS DO BRASIL S.A']);
            Bank::create(['Number' => '409', 'Name' => 'UNIBANCO - UNIAO DOS BANCOS BRASILEIROS']);
            Bank::create(['Number' => '412', 'Name' => 'BANCO NACIONAL DA BAHIA S.A']);
            Bank::create(['Number' => '415', 'Name' => 'BANCO NACIONAL S.A']);
            Bank::create(['Number' => '420', 'Name' => 'BANCO NACIONAL DO NORTE S.A']);
            Bank::create(['Number' => '422', 'Name' => 'BANCO SAFRA S.A']);
            Bank::create(['Number' => '424', 'Name' => 'BANCO NOROESTE S.A']);
            Bank::create(['Number' => '434', 'Name' => 'BANCO FORTALEZA S.A']);
            Bank::create(['Number' => '453', 'Name' => 'BANCO RURAL S.A']);
            Bank::create(['Number' => '456', 'Name' => 'BANCO TOKIO S.A']);
            Bank::create(['Number' => '464', 'Name' => 'BANCO SUMITOMO BRASILEIRO S.A']);
            Bank::create(['Number' => '466', 'Name' => 'BANCO MITSUBISHI BRASILEIRO S.A']);
            Bank::create(['Number' => '472', 'Name' => 'LLOYDS BANK PLC']);
            Bank::create(['Number' => '473', 'Name' => 'BANCO FINANCIAL PORTUGUES S.A']);
            Bank::create(['Number' => '477', 'Name' => 'CITIBANK N.A']);
            Bank::create(['Number' => '479', 'Name' => 'BANCO DE BOSTON S.A']);
            Bank::create(['Number' => '480', 'Name' => 'BANCO PORTUGUES DO ATLANTICO-BRASIL S.A']);
            Bank::create(['Number' => '483', 'Name' => 'BANCO AGRIMISA S.A.']);
            Bank::create(['Number' => '487', 'Name' => 'DEUTSCHE BANK S.A - BANCO ALEMAO']);
            Bank::create(['Number' => '488', 'Name' => 'BANCO J. P. MORGAN S.A']);
            Bank::create(['Number' => '489', 'Name' => 'BANESTO BANCO URUGAUAY S.A']);
            Bank::create(['Number' => '492', 'Name' => 'INTERNATIONALE NEDERLANDEN BANK N.V.']);
            Bank::create(['Number' => '493', 'Name' => 'BANCO UNION S.A.C.A']);
            Bank::create(['Number' => '494', 'Name' => 'BANCO LA REP. ORIENTAL DEL URUGUAY']);
            Bank::create(['Number' => '495', 'Name' => 'BANCO LA PROVINCIA DE BUENOS AIRES']);
            Bank::create(['Number' => '496', 'Name' => 'BANCO EXTERIOR DE ESPANA S.A']);
            Bank::create(['Number' => '498', 'Name' => 'CENTRO HISPANO BANCO']);
            Bank::create(['Number' => '499', 'Name' => 'BANCO IOCHPE S.A']);
            Bank::create(['Number' => '501', 'Name' => 'BANCO BRASILEIRO IRAQUIANO S.A.']);
            Bank::create(['Number' => '502', 'Name' => 'BANCO SANTANDER S.A']);
            Bank::create(['Number' => '504', 'Name' => 'BANCO MULTIPLIC S.A']);
            Bank::create(['Number' => '505', 'Name' => 'BANCO GARANTIA S.A']);
            Bank::create(['Number' => '600', 'Name' => 'BANCO LUSO BRASILEIRO S.A']);
            Bank::create(['Number' => '601', 'Name' => 'BFC BANCO S.A.']);
            Bank::create(['Number' => '602', 'Name' => 'BANCO PATENTE S.A']);
            Bank::create(['Number' => '604', 'Name' => 'BANCO INDUSTRIAL DO BRASIL S.A']);
            Bank::create(['Number' => '607', 'Name' => 'BANCO SANTOS NEVES S.A']);
            Bank::create(['Number' => '608', 'Name' => 'BANCO OPEN S.A']);
            Bank::create(['Number' => '610', 'Name' => 'BANCO V.R. S.A']);
            Bank::create(['Number' => '611', 'Name' => 'BANCO PAULISTA S.A']);
            Bank::create(['Number' => '612', 'Name' => 'BANCO GUANABARA S.A']);
            Bank::create(['Number' => '613', 'Name' => 'BANCO PECUNIA S.A']);
            Bank::create(['Number' => '616', 'Name' => 'BANCO INTERPACIFICO S.A']);
            Bank::create(['Number' => '617', 'Name' => 'BANCO INVESTOR S.A.']);
            Bank::create(['Number' => '618', 'Name' => 'BANCO TENDENCIA S.A']);
            Bank::create(['Number' => '621', 'Name' => 'BANCO APLICAP S.A.']);
            Bank::create(['Number' => '622', 'Name' => 'BANCO DRACMA S.A']);
            Bank::create(['Number' => '623', 'Name' => 'BANCO PANAMERICANO S.A']);
            Bank::create(['Number' => '624', 'Name' => 'BANCO GENERAL MOTORS S.A']);
            Bank::create(['Number' => '625', 'Name' => 'BANCO ARAUCARIA S.A']);
            Bank::create(['Number' => '626', 'Name' => 'BANCO FICSA S.A']);
            Bank::create(['Number' => '627', 'Name' => 'BANCO DESTAK S.A']);
            Bank::create(['Number' => '628', 'Name' => 'BANCO CRITERIUM S.A']);
            Bank::create(['Number' => '629', 'Name' => 'BANCORP BANCO COML. E. DE INVESTMENTO']);
            Bank::create(['Number' => '630', 'Name' => 'BANCO INTERCAP S.A']);
            Bank::create(['Number' => '633', 'Name' => 'BANCO REDIMENTO S.A']);
            Bank::create(['Number' => '634', 'Name' => 'BANCO TRIANGULO S.A']);
            Bank::create(['Number' => '635', 'Name' => 'BANCO DO ESTADO DO AMAPA S.A']);
            Bank::create(['Number' => '637', 'Name' => 'BANCO SOFISA S.A']);
            Bank::create(['Number' => '638', 'Name' => 'BANCO PROSPER S.A']);
            Bank::create(['Number' => '639', 'Name' => 'BIG S.A. - BANCO IRMAOS GUIMARAES']);
            Bank::create(['Number' => '640', 'Name' => 'BANCO DE CREDITO METROPOLITANO S.A']);
            Bank::create(['Number' => '641', 'Name' => 'BANCO EXCEL ECONOMICO S/A']);
            Bank::create(['Number' => '643', 'Name' => 'BANCO SEGMENTO S.A']);
            Bank::create(['Number' => '645', 'Name' => 'BANCO DO ESTADO DE RORAIMA S.A']);
            Bank::create(['Number' => '647', 'Name' => 'BANCO MARKA S.A']);
            Bank::create(['Number' => '648', 'Name' => 'BANCO ATLANTIS S.A']);
            Bank::create(['Number' => '649', 'Name' => 'BANCO DIMENSAO S.A']);
            Bank::create(['Number' => '650', 'Name' => 'BANCO PEBB S.A']);
            Bank::create(['Number' => '652', 'Name' => 'BANCO FRANCES E BRASILEIRO SA']);
            Bank::create(['Number' => '653', 'Name' => 'BANCO INDUSVAL S.A']);
            Bank::create(['Number' => '654', 'Name' => 'BANCO A. J. RENNER S.A']);
            Bank::create(['Number' => '655', 'Name' => 'BANCO VOTORANTIM S.A.']);
            Bank::create(['Number' => '656', 'Name' => 'BANCO MATRIX S.A']);
            Bank::create(['Number' => '657', 'Name' => 'BANCO TECNICORP S.A']);
            Bank::create(['Number' => '658', 'Name' => 'BANCO PORTO REAL S.A']);
            Bank::create(['Number' => '702', 'Name' => 'BANCO SANTOS S.A']);
            Bank::create(['Number' => '705', 'Name' => 'BANCO INVESTCORP S.A.']);
            Bank::create(['Number' => '707', 'Name' => 'BANCO DAYCOVAL S.A']);
            Bank::create(['Number' => '711', 'Name' => 'BANCO VETOR S.A.']);
            Bank::create(['Number' => '713', 'Name' => 'BANCO CINDAM S.A']);
            Bank::create(['Number' => '715', 'Name' => 'BANCO VEGA S.A']);
            Bank::create(['Number' => '718', 'Name' => 'BANCO OPERADOR S.A']);
            Bank::create(['Number' => '719', 'Name' => 'BANCO PRIMUS S.A']);
            Bank::create(['Number' => '720', 'Name' => 'BANCO MAXINVEST S.A']);
            Bank::create(['Number' => '721', 'Name' => 'BANCO CREDIBEL S.A']);
            Bank::create(['Number' => '722', 'Name' => 'BANCO INTERIOR DE SAO PAULO S.A']);
            Bank::create(['Number' => '724', 'Name' => 'BANCO PORTO SEGURO S.A']);
            Bank::create(['Number' => '725', 'Name' => 'BANCO FINABANCO S.A']);
            Bank::create(['Number' => '726', 'Name' => 'BANCO UNIVERSAL S.A']);
            Bank::create(['Number' => '728', 'Name' => 'BANCO FITAL S.A']);
            Bank::create(['Number' => '729', 'Name' => 'BANCO FONTE S.A']);
            Bank::create(['Number' => '730', 'Name' => 'BANCO COMERCIAL PARAGUAYO S.A']);
            Bank::create(['Number' => '731', 'Name' => 'BANCO GNPP S.A.']);
            Bank::create(['Number' => '732', 'Name' => 'BANCO PREMIER S.A.']);
            Bank::create(['Number' => '733', 'Name' => 'BANCO NACOES S.A.']);
            Bank::create(['Number' => '734', 'Name' => 'BANCO GERDAU S.A']);
            Bank::create(['Number' => '735', 'Name' => 'BANCO NEON']);
            Bank::create(['Number' => '736', 'Name' => 'BANCO UNITED S.A']);
            Bank::create(['Number' => '737', 'Name' => 'THECA']);
            Bank::create(['Number' => '738', 'Name' => 'MARADA']);
            Bank::create(['Number' => '739', 'Name' => 'BGN']);
            Bank::create(['Number' => '740', 'Name' => 'BCN BARCLAYS']);
            Bank::create(['Number' => '741', 'Name' => 'BRP']);
            Bank::create(['Number' => '742', 'Name' => 'EQUATORIAL']);
            Bank::create(['Number' => '743', 'Name' => 'BANCO EMBLEMA S.A']);
            Bank::create(['Number' => '744', 'Name' => 'THE FIRST NATIONAL BANK OF BOSTON']);
            Bank::create(['Number' => '745', 'Name' => 'CITIBAN N.A.']);
            Bank::create(['Number' => '746', 'Name' => 'MODAL S\A']);
            Bank::create(['Number' => '747', 'Name' => 'RAIBOBANK DO BRASIL']);
            Bank::create(['Number' => '748', 'Name' => 'SICREDI']);
            Bank::create(['Number' => '749', 'Name' => 'BRMSANTIL SA']);
            Bank::create(['Number' => '750', 'Name' => 'BANCO REPUBLIC NATIONAL OF NEW YORK (BRA']);
            Bank::create(['Number' => '751', 'Name' => 'DRESDNER BANK LATEINAMERIKA-BRASIL S/A']);
            Bank::create(['Number' => '752', 'Name' => 'BANCO BANQUE NATIONALE DE PARIS BRASIL S']);
            Bank::create(['Number' => '753', 'Name' => 'BANCO COMERCIAL URUGUAI S.A.']);
            Bank::create(['Number' => '755', 'Name' => 'BANCO MERRILL LYNCH S.A']);
            Bank::create(['Number' => '756', 'Name' => 'BANCO COOPERATIVO DO BRASIL S.A.']);
            Bank::create(['Number' => '757', 'Name' => 'BANCO KEB DO BRASIL S.A.']);
        }
        if(Bank::where('number', '260')->first()->title_color !== '#ba4de3'){
            echo "\nalterou a cor do banco 260";
            Bank::where('number', '260')->first()->update(['title_color'  => '#ba4de3',
                'body_color'   => '#d494ec']);
        }
        if(Bank::where('number', '104')->first()->title_color !== '#0369b9') {
            echo "\nalterou a cor do banco 104\n";
            Bank::where('number', '104')->first()->update(['title_color' => '#0369b9',
                'body_color' => '#f3bb5c']);
        }
    }
}
