# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.2-fpm

pipelines:
  default:
    - step:
        name: Build and Run tests
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y --no-install-recommends libfreetype6-dev libjpeg-dev libpng-dev libwebp-dev
          - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/inclue/ --with-webp-dir=/usr/include/
          - docker-php-ext-install gd
          - apt-get install -y --no-install-recommends libgmp-dev
          - docker-php-ext-install gmp
          - docker-php-ext-install pdo_mysql
          - docker-php-ext-enable opcache
          - docker-php-ext-install zip
          - docker-php-ext-install bcmath && docker-php-ext-configure bcmath && docker-php-ext-enable bcmath
          - apt-get autoclean -y
          - rm -rf /var/lib/apt/lists/*
          - rm -rf /tmp/pear/
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpunit
    - step:
        name: Deploy to test
        deployment: Production
        script:
          - echo "Deploying to test environment"
          - apt-get update
          - apt-get install -y ssh
          - ssh -i /opt/atlassian/pipelines/agent/ssh/id_rsa bitbucket@$ip -t cd /var/www/personal-administration

