name: Deploy Laravel Application to Production Server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4.34

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Synchronize Files To Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          TARGET: "/var/www/tmpdeploy"

      - name: Run Remote/Artisan Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo touch /var/www/tmpdeploy/.env
            sudo chmod -R 777 /var/www/tmpdeploy/.env
            sudo echo "${{ secrets.ENV }}" >> /var/www/tmpdeploy/.env
            php /var/www/tmpdeploy/artisan migrate --force
            php /var/www/tmpdeploy/artisan optimize
            sudo rm -Rf /var/www/testdeploy
            sudo mv /var/www/tmpdeploy /var/www/testdeploy
            sudo mkdir /var/www/tmpdeploy
            sudo chmod -R 777 /var/www/tmpdeploy
